applications/vacancy/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path(
        '',
        views.vacancy_list,
        name='vacancy_list',
    ),

    path(
        '<int:pk>/',
        views.vacancy_detail,
        name='vacancy_detail',
    ),

    path(
        'company/',
        views.company_list,
        name='company_list',
    ),

    path(
        'company/<int:pk>/',
        views.company_detail,
        name='company_detail',
    ),

    path(
        'autocomplete/',
        views.autocomplete,
        name='autocomplete',
    ),

    path(
        'search/',
        views.VacancySearchView.as_view(),
        name='haystack_search',
    ),
]

settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path


urlpatterns = [
    path(
        'admin/',
        admin.site.urls,
    ),
]

urlpatterns += [
    path(
        'ckeditor/',
        include('ckeditor_uploader.urls'),
    ),
]

urlpatterns += [
    path(
        '',
        include(('applications.main.urls', 'main'), namespace='main'),
    ),

    path(
        'vacancy/',
        include(('applications.vacancy.urls', 'vacancy'), namespace='vacancy'),
    ),
]

urlpatterns += staticfiles_urlpatterns() + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

applications/vacancy/models.py
from django.db import models
from django.urls import reverse, reverse_lazy

from applications.core import models as core_models


class VacancySite(core_models.Date):
    """
    Сайт откуда взяты вакансии
    """

    class Country(models.TextChoices):
        RUSSIA = 'RUS', 'Россия'
        UKRAINE = 'UKR', 'Украина'
        BELARUS = 'BLR', 'Белоруссия'
        KAZAKHSTAN = 'KAZ', 'Казахстан'
        UZBEKISTAN = 'UZB', 'Узбекистан'
        AMERICA = 'USA', 'США'
        EUROPE = 'EU', 'Европейский Союз'
        ENGLAND = 'GBR', 'Великобритания'
        GERMANY = 'DEU', 'Германия'
        POLAND = 'POL', 'Польша'

    name = models.CharField(
        verbose_name='Название сайта',
        max_length=250,
        blank=True,
    )

    link = models.URLField(
        verbose_name='Ссылка на сайт',
        max_length=1000,
    )

    country = models.CharField(
        verbose_name='Страна',
        max_length=3,
        choices=Country.choices,
        default=Country.RUSSIA,
        blank=True,
    )

    description = models.TextField(
        verbose_name='Описание',
        blank=True,
    )

    class Meta:
        verbose_name = 'сайт вакансий'
        verbose_name_plural = 'сайты вакансий'

    def __str__(self):
        return self.link


class ScrapingLink(core_models.Date):
    """
    Ссылка для скрапинга вакансий
    """

    skill = models.CharField(
        verbose_name='Навык',
        max_length=100,
    )

    link = models.URLField(
        verbose_name='Ссылка для скрапинга',
        max_length=1000,
        help_text='Пример: https://career.habr.com/vacancies?q=python&sort=date&type=all',
    )

    scraping_site = models.ForeignKey(
        verbose_name='Скрапинг на сайте',
        to=VacancySite,
        on_delete=models.CASCADE,
    )

    description = models.TextField(
        verbose_name='Описание',
        blank=True,
    )

    class Meta:
        verbose_name = 'ссылку для скрапинга'
        verbose_name_plural = 'ссылки для скрапинга'

    def __str__(self):
        return self.link


class Company(core_models.Common):
    """
    Компания разместившая вакансию
    """

    name = models.CharField(verbose_name='Название компании', max_length=250)
    slug = models.SlugField(verbose_name='URL-имя', max_length=250, blank=True)
    about = models.TextField(verbose_name='О компании', blank=True)
    industry = models.CharField(verbose_name='Отрасль', max_length=250, blank=True)
    employees = models.CharField(verbose_name='Количество сотрудников', max_length=250, blank=True)
    verified = models.CharField(verbose_name='Компания проверена', max_length=250, blank=True)
    website = models.CharField(verbose_name='Сайт компании', max_length=250, blank=True)
    phone = models.CharField(verbose_name='Телефон компании', max_length=250, blank=True)
    email = models.CharField(verbose_name='E-mail компании', max_length=250, blank=True)
    company_id = models.CharField(verbose_name='ID компании', max_length=250, blank=True)
    scraping_site = models.ForeignKey(verbose_name='Компания с сайта', to=VacancySite, on_delete=models.SET_NULL, null=True, blank=True)
    about_short = models.TextField(verbose_name='О компании (сокращённо)', blank=True)
    skills = models.CharField(verbose_name='Навыки', max_length=1000, blank=True)
    company_ratings = models.CharField(verbose_name='Рейтинги и оценки', max_length=250, blank=True)
    rating = models.CharField(verbose_name='Средний рейтинг компании', max_length=100, blank=True)
    statistics = models.CharField(verbose_name='Статистика', max_length=1000, blank=True)
    addresses = models.TextField(verbose_name='Адреса компании', blank=True)
    contacts = models.TextField(verbose_name='Контакты', blank=True)
    links = models.TextField(verbose_name='Ссылки', blank=True)
    members  =  models.JSONField(verbose_name='Персонал компании', blank=True, null=True)
    photo = models.JSONField(verbose_name='Фото компании', blank=True, null=True)
    video = models.JSONField(verbose_name='Видео компании', blank=True, null=True)

    class Meta:
        verbose_name = 'компанию'
        verbose_name_plural = 'компании'

    def get_absolute_url(self):
        return reverse('vacancy:company_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class Vacancy(core_models.Common):
    """
    Вакансия
    """

    title = models.CharField(verbose_name='Название вакансии', max_length=250)
    slug = models.SlugField(verbose_name='URL-имя', max_length=250, blank=True)
    body = models.TextField(verbose_name='Текст вакансии')
    salary = models.CharField(verbose_name='Зарплата', max_length=1000, blank=True)
    address = models.CharField(verbose_name='Адрес работы', max_length=1000, blank=True)
    place = models.CharField(verbose_name='Место работы', max_length=1000, blank=True)
    requirements = models.CharField(verbose_name='Условия и требования', max_length=1000, blank=True)
    language = models.CharField(verbose_name='Знание языков', max_length=1000, blank=True)
    contact_name = models.CharField(verbose_name='Контактное имя', max_length=1000, blank=True)
    contact_phone = models.CharField(verbose_name='Контактный телефон', max_length=1000, blank=True)
    contact_email = models.CharField(verbose_name='Контактный e-mail', max_length=1000, blank=True)
    company = models.ForeignKey(verbose_name='Компания', to=Company, on_delete=models.CASCADE, null=True, blank=True)
    vacancy_id = models.CharField(verbose_name='ID вакансии', max_length=250)
    scraping_site = models.ForeignKey(verbose_name='Вакансия с сайта', to=VacancySite, on_delete=models.SET_NULL, null=True, blank=True)
    scraping_link = models.ForeignKey(verbose_name='Ссылка для скрапинга', to=ScrapingLink, on_delete=models.SET_NULL, null=True, blank=True)
    text_date = models.CharField(verbose_name='День создания (текст с сайта вакансий)', max_length=250, blank=True)
    datetime = models.DateTimeField(verbose_name='Дата и время создания на сайте вакансий', blank=True, null=True)

    class Meta:
        ordering = ['-datetime']
        verbose_name = 'вакансию'
        verbose_name_plural = 'вакансии'

    def get_absolute_url(self):
        return reverse_lazy('vacancy:vacancy_detail', kwargs={'pk': self.pk})
    get_absolute_url.short_description = 'ссылка'

    def __str__(self):
        return self.title

applications/vacancy/views.py
from haystack.query import SearchQuerySet, SQ
from haystack.generic_views import SearchView
from datetime import date, timedelta
from django.shortcuts import render, get_object_or_404
from django.forms.models import model_to_dict
from django.http import JsonResponse

from .models import Vacancy, Company


def vacancy_list(request):
    vacancies = Vacancy.published.all().order_by('-datetime')
    return render(request, 'vacancy/vacancy/list.html', {'vacancies': vacancies, 'vacancies_count': len(vacancies)})


def vacancy_detail(request, pk):
    vacancy = get_object_or_404(Vacancy, pk=pk)
    vacancy_dict = model_to_dict(vacancy)
    stop_field = ['id', 'title', 'body', 'date', 'slug', 'status', 'company', 'vacancy_id']
    return render(
        request,
        'vacancy/vacancy/detail.html',
        {'vacancy': vacancy, 'vacancy_dict': vacancy_dict, 'stop_field': stop_field},
    )


def company_list(request):
    companies = Company.objects.all()
    return render(request, 'vacancy/company/list.html', {'companies': companies, 'companies_count': len(companies)})


def company_detail(request, pk):
    company = get_object_or_404(Company, pk=pk)
    company_dict = model_to_dict(company)
    stop_field = ['name', 'created', 'photos']
    return render(
        request,
        'vacancy/company/detail.html',
        {'company': company, 'company_dict': company_dict, 'stop_field': stop_field},
    )


def autocomplete(request):
    results = []
    max_items = 50
    q = request.GET.get('q')
    if q:
        title_sqs = SearchQuerySet().autocomplete(title_auto=q).order_by('-datetime')
        body_sqs = SearchQuerySet().autocomplete(body_auto=q).order_by('-datetime')
        sqs = title_sqs | body_sqs
        results = [[result.object.title, str(result.object.pk)] for result in sqs[:max_items]]
    return JsonResponse({'results': results})


class VacancySearchView(SearchView):

    def get_search_result(self):
        qs = self.get_queryset()
        q = None
        day = None
        sort_by = None
        results = []

        if self.request.method == "GET":
            q = self.request.GET.get('q', '')
            day = self.request.GET.get('start_day', '')
            sort_by = self.request.GET.get('sort_by', '')

        if q:
            if day and day.isdigit():
                start_date = date.today() - timedelta(days=int(day))
                title_results = qs.autocomplete(title_auto=q).filter(created__gte=start_date)
                body_results = qs.autocomplete(body_auto=q).filter(created__gte=start_date)
            else:
                title_results = qs.autocomplete(title_auto=q)
                body_results = qs.autocomplete(body_auto=q)

            results = title_results | body_results

        if results:
            if sort_by == 'new':
                results = results.order_by('-datetime')
            elif sort_by == 'old':
                results = results.order_by('datetime')

        return results

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context.update({'results_count': len(context['object_list'])})
        return context

    def form_valid(self, form):
        self.queryset = self.get_search_result()
        context = self.get_context_data(
            **{
                self.form_name: form,
                "query": form.cleaned_data.get(self.search_field),
                "object_list": self.queryset,
            }
        )
        return self.render_to_response(context)

applications/vacancy/templates/search/search.html
{% extends 'base.html' %}
{% load highlight %}
{% load core_tags %}
{% load static %}


{% block title %}Поиск{% endblock %}


{% block content %}
    <section>
        <h2 style="text-align: center;">Найти работу</h2>

        <form id="searchForm" action="{% url 'vacancy:haystack_search' %}" class="autocomplete" method="get">
            {% csrf_token %}

            <label for="q">Вакансия:</label>
            <input type="text" id="q" name="q" placeholder="Введите слово для поиска"  autocomplete="off" required>

            <label for="id_start_day">За время:</label>
            <select id="id_start_day" name="start_day" size="7">
                <option value="1">1 день</option>
                <option value="3">3 дня</option>
                <option value="7">7 дней</option>
                <option value="10">10 дней</option>
                <option value="14">14 дней</option>
                <option value="30">30 дней</option>
                <option value="364">за год</option>
            </select>

            <label for="id_sort_by">Сортировать результаты поиска:</label>
            <select id="id_sort_by" name="sort_by" size="2">
              <option value="new">Сначало новые</option>
              <option value="old">Сначало старые</option>
            </select>

            <br />
            <button type="submit">Найти</button>
        </form>

        <div class="js-autocomplete-result"></div>

        <div class="search-results">
            {% if query %}
                <h5>
                    <span class="highlighted">{{ results_count }}</span>
                    {{ results_count|ru_plural:'результат,результата,результатов' }}
                    поиска для <span class="highlighted">{{ query }}</span>
                </h5>

                {% include 'pagination.html' with page=page_obj %}

                {% for result in page_obj.object_list %}
                    <p>
                        <a href="{{ result.object.get_absolute_url }}">
                          {% highlight result.object.title with query html_tag "span" css_class "highlighted"  max_length 200 %}
                        </a>
                    </p>
                    <p>{% highlight result.object.body with query html_tag "span" css_class "highlighted"  max_length 2000 %}</p>
                {% empty %}
                    <p>Ничего не найдено.</p>
                {% endfor %}

                {% include 'pagination.html' with page=page_obj %}
            {% endif %}
        </div>
    </section>


    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <script type="text/javascript">
        // https://django-haystack.readthedocs.io/en/latest/autocomplete.html#example-implementation
        var Autocomplete = function(options) {
          this.form_selector = options.form_selector
          this.url = options.url || '/vacancy/autocomplete/'
          this.delay = parseInt(options.delay || 300)
          this.minimum_length = parseInt(options.minimum_length || 3)
          this.form_elem = null
          this.query_box = null
          this.result_selector = options.result_selector
        }

        Autocomplete.prototype.setup = function() {
          var self = this

          this.form_elem = $(this.form_selector)
          this.query_box = this.form_elem.find('input[name=q]')
          this.result_selector = $(this.result_selector)

          // Watch the input box.
          this.query_box.on('keyup', function() {
            var query = self.query_box.val()

            if(query.length < self.minimum_length) {
              return false
            }

            self.fetch(query)
          })

          // On selecting a result, populate the search field.
          this.form_elem.on('click', '.ac-result', function(ev) {
            self.query_box.val($(this).text())
            $('.ac-results').remove()
            return false
          })
        }

        Autocomplete.prototype.fetch = function(query) {
          var self = this

          $.ajax({
            url: this.url
          , data: {
              'q': query
            }
          , success: function(data) {
              self.show_results(data)
            }
          })
        }

        Autocomplete.prototype.show_results = function(data) {
          // Remove any existing results.
          $('.ac-results').remove()
          $('.search-results').remove()

          var results = data.results || []
          var results_wrapper = $('<div class="ac-results"></div>')
          var results_length = $('<div class="results_length"></div>')
          var base_elem = $('<div class="result-wrapper"><a href="#" class="ac-result"></a></div>')

          if(results.length > 0) {
            results_wrapper.append(results_length.text(results.length + ' результатов'))
            for(var res_offset in results) {
              var elem = base_elem.clone()
              // Don't use .html(...) here, as you open yourself to XSS.
              // Really, you should use some form of templating.
              elem.find('.ac-result').text(results[res_offset][0]).attr('href', '/vacancy/' + results[res_offset][1] + '/')
              results_wrapper.append(elem)
            }
          }
          else {
            var elem = base_elem.clone()
            elem.text("Ни чего не найдено.")
            results_wrapper.append(elem)
          }

          this.result_selector.append(results_wrapper)
        }

        $(document).ready(function() {
          window.autocomplete = new Autocomplete({
            form_selector: '.autocomplete',
            url: '{% url "vacancy:autocomplete" %}',
            result_selector: '.js-autocomplete-result'
          })
          window.autocomplete.setup()
        })
    </script>

{% endblock %}