applications/main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path(
        '',
        views.IndexView.as_view(),
        name='index',
    ),

    path(
        'about/',
        views.AboutView.as_view(),
        name='about',
    ),
]

applications/vacancy/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path(
        '',
        views.vacancy_list,
        name='vacancy_list',
    ),

    path(
        '<int:pk>/',
        views.vacancy_detail,
        name='vacancy_detail',
    ),

    path(
        'company/',
        views.company_list,
        name='company_list',
    ),

    path(
        'company/<int:pk>/',
        views.company_detail,
        name='company_detail',
    ),

    path(
        'autocomplete/',
        views.autocomplete,
        name='autocomplete',
    ),

    path(
        'search/',
        views.VacancySearchView.as_view(),
        name='haystack_search',
    ),
]

settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path


urlpatterns = [
    path(
        'admin/',
        admin.site.urls,
    ),
]

urlpatterns += [
    path(
        'ckeditor/',
        include('ckeditor_uploader.urls'),
    ),
]

urlpatterns += [
    path(
        '',
        include(('applications.main.urls', 'main'), namespace='main'),
    ),

    path(
        'vacancy/',
        include(('applications.vacancy.urls', 'vacancy'), namespace='vacancy'),
    ),
]

urlpatterns += staticfiles_urlpatterns() + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="ru">
<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, viewport-fit=cover">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="imagetoolbar" content="no">
	<meta name="msthemecompatible" content="no">
	<meta name="cleartype" content="on">
	<meta name="HandheldFriendly" content="True">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

	{% comment %}
	<link sizes="152x152" href="{% static 'images/apple-touch-icon-152x152.png' %}" rel="apple-touch-icon">
	<link sizes="144x144" href="{% static 'images/apple-touch-icon-144x144.png' %}" rel="apple-touch-icon">
	<link sizes="120x120" href="{% static 'images/apple-touch-icon-120x120.png' %}" rel="apple-touch-icon">
	<link sizes="114x114" href="{% static 'images/apple-touch-icon-114x114.png' %}" rel="apple-touch-icon">
	<link sizes="76x76" href="{% static 'images/apple-touch-icon-76x76.png' %}" rel="apple-touch-icon">
	<link sizes="72x72" href="{% static 'images/apple-touch-icon-72x72.png' %}" rel="apple-touch-icon">
	<link sizes="60x60" href="{% static 'images/apple-touch-icon-60x60.png' %}" rel="apple-touch-icon">
	<link sizes="57x57" href="{% static 'images/apple-touch-icon-57x57.png' %}" rel="apple-touch-icon">
	<link sizes="196x196" href="{% static 'images/favicon-196x196.png' %}" rel="icon" type="image/png">
	<link sizes="128x128" href="{% static 'images/favicon-128.png' %}" rel="icon" type="image/png">
	<link sizes="96x96" href="{% static 'images/favicon-96x96.png' %}" rel="icon" type="image/png">
	<link sizes="32x32" href="{% static 'images/favicon-32x32.png' %}" rel="icon" type="image/png">
	<link sizes="16x16" href="{% static 'images/favicon-16x16.png' %}" rel="icon" type="image/png">
	<meta name="application-name" content="Example">
	<meta name="msapplication-tooltip" content="Example">
	<meta name="msapplication-TileColor" content="#ffffff">
	<meta name="msapplication-starturl" content="http://example.ru">
	<meta name="msapplication-tap-highlight" content="no">
	<meta name="msapplication-square310x310logo" content="{% static 'images/mstile-310x310.png' %}">
	<meta name="msapplication-wide310x150logo" content="{% static 'images/mstile-310x150.png' %}">
	<meta name="msapplication-square150x150logo" content="{% static 'images/mstile-150x150.png' %}">
	<meta name="msapplication-TileImage" content="{% static 'images/mstile-144x144.png' %}">
	<meta name="msapplication-square70x70logo" content="{% static 'images/mstile-70x70.png' %}">
	{% endcomment %}

	<title>{% block full_title %}{{ preference.site_title }} - {% block title %}{% endblock %}{% endblock full_title %}</title>

	<link rel="canonical" href="{{ request.path }}">
	<link rel="preload" href="{% static 'styles/base.css' %}" as="style">
	{% comment %} <link rel="stylesheet" href="{% static 'styles/bootstrap/base.css' %}"> {% endcomment %}
	<link rel="stylesheet" href="{% static 'styles/base.css' %}">

	{% block head %}{% endblock head %}

	{{ preference.header_html|safe }}

</head>
<body>
	<header>
		<h1>Поиск работы</h1>
	</header>

	<nav>
		<a href={% url 'main:index' %}>На главную</a>
		<a href={% url 'vacancy:vacancy_list' %}>Все вакансии</a>
		<a href={% url 'vacancy:company_list' %}>Все компании</a>
		<a href={% url 'vacancy:haystack_search' %}>Поиск</a>
		<a href={% url 'main:about' %}>О нас</a>
	</nav>

	{% block content %}{% endblock content %}

	<footer>
		<p>&copy; 2024 Поиск работы для IT специалистов. Все права защищены.</p>

		{{ preference.footer_html|safe }}
	</footer>

</body>
</html>

templates/pagination.html
{% if page.has_previous or page.has_next %}
  <div class="pagination">
      {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">&laquo; Предыдущая </a>{% endif %}

      {{ page.number }} из {{ page.paginator.num_pages }}

      {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}"> Следующая &raquo;</a>{% endif %}
  </div>
{% endif %}